// general-headers.interceptor.ts
import {Injectable} from '@angular/core';
import {HttpEvent, HttpHandler, HttpInterceptor, HttpRequest} from '@angular/common/http';
import {Observable} from 'rxjs';

@Injectable()
export class GeneralHeadersInterceptor implements HttpInterceptor {
  private token = 'eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJvaWQiOiI3Njg0NDczNS00YmEwLTQ1YjYtYjI3Zi05ZDQ0YzhjODg3ZjAiLCJzdWIiOiI3Njg0NDczNS00YmEwLTQ1YjYtYjI3Zi05ZDQ0YzhjODg3ZjAiLCJuYW1lIjoiSHVzc2VpbiBIYXNzYW4iLCJnaXZlbl9uYW1lIjoiSHVzc2VpbiIsImZhbWlseV9uYW1lIjoiSGFzc2FuIiwiam9iVGl0bGUiOiJGcm9udGVuZCBUZWNoIExlYWQiLCJlbWFpbHMiOlsiaHVzc2Vpbi5oYXNzYW5AaW50ZWdyYW50LmNvbSJdLCJleHRlbnNpb25fY3BjbGFpbV9idWNrZXRfbmFtZSI6ImNwLWludGVncmFudC0yMDIzMDIwMiIsImV4dGVuc2lvbl9jcGNsYWltX3BhcnRuZXJfaWQiOiIyN2VkNzZjZS1iZGI5LTQxZjAtYWNhMi1hMTJjNTllZDJkMTciLCJleHRlbnNpb25fY3BjbGFpbV9wYXJ0bmVyX25hbWUiOiJJbnRlZ3JhbnQiLCJleHRlbnNpb25fY3BjbGFpbV9wYXJ0bmVyX3R5cGUiOiJEaXN0cmlidXRvciIsImV4dGVuc2lvbl9jcGNsYWltX3BhcnRuZXJfc2VydmljZXMiOiJbe1wiU2VydmljZUNvZGVcIjpcInJlY3ljbGFiaWxpdHlfY2hlY2tcIixcIkFsbFByb2R1Y3RzXCI6dHJ1ZX0se1wiU2VydmljZUNvZGVcIjpcImNvbXBhdGliaWxpdHlfY2hlY2tcIixcIkFsbFByb2R1Y3RzXCI6dHJ1ZX0se1wiU2VydmljZUNvZGVcIjpcInJlcXVlc3RzXCIsXCJBbGxQcm9kdWN0c1wiOnRydWV9LHtcIlNlcnZpY2VDb2RlXCI6XCJwcm9qZWN0XCIsXCJBbGxQcm9kdWN0c1wiOnRydWV9LHtcIlNlcnZpY2VDb2RlXCI6XCJwcm9kdWN0X2Fzc2V0c1wiLFwiQWxsUHJvZHVjdHNcIjp0cnVlfSx7XCJTZXJ2aWNlQ29kZVwiOlwicHJvamVjdF9hc3NldHNcIixcIkFsbFByb2R1Y3RzXCI6dHJ1ZX0se1wiU2VydmljZUNvZGVcIjpcImdlbmVyYWxfYXNzZXRzXCIsXCJBbGxQcm9kdWN0c1wiOnRydWV9XSIsInRmcCI6IkIyQ18xX1NvZnR3YXJlRW5naW5lZXJpbmdDdXN0b21lclBvcnRhbCIsIm5vbmNlIjoiNjM0YzllZTEtZTc1OS00OGI4LWEyMGMtM2RjYTlkYjQzMDNhIiwic2NwIjoiYXBpLWFjY2VzcyIsImF6cCI6IjU0NDUwYzg3LWJmODUtNDA5NC1hODhkLTk1NDhjNDI5YTJlOCIsInZlciI6IjEuMCIsImlhdCI6MTcxNTY0MzM5MywiYXVkIjoiYWI2ZjRmNzUtMmI2ZS00MGVlLTg1YTctZGUzN2UzMjRjZmM5IiwiZXhwIjoxNzE1NjQ2OTkzLCJpc3MiOiJodHRwczovL2FwdGFyYjJjZGV2LmIyY2xvZ2luLmNvbS9lNDI0Yjg5My1jYTU1LTQ5ZWQtYWY4Zi1kOTY4ZGE1MTgwZTIvdjIuMC8iLCJuYmYiOjE3MTU2NDMzOTN9.ACA71FJ3NLIfWeDhlqGVGT-jOe50SFH4FIee3mIVU31P5jFBzRufMJCT7NJCAixBuu2e_pEFZlwp5EO8AegwZQX9VNvNlfAs6-sZUApxwhuM6MgBTKs0r4yFjYk3i77Vcri-TEtmGz9HoOGZjTw9_DISTMIAork1PwE_oaWV5zuX7T1t5XeYoOMkXfzdWWQeInws2iKa3g_9c9QjeE0ZGi7ToDRjH9aDn6AHCtcGmatCQ-Rvg7RewcxV4uQe3E5sF0Baskkf91E97mMZyLhkQ-zobs9-D3GFfEMS2auAR-OBwNdv7XSYS7ml_jy5rhPCcHk9ULeL_G0rdExGFLXipA'

  intercept(req : HttpRequest<any>, {handle} : HttpHandler) : Observable<HttpEvent<any>> {
    // Clone the request to add new headers
    const clonedRequest = req.clone({
      setHeaders: {
        'Authorization': `Bearer ${this.token}`, // Replace with actual header
        // Add more headers as needed
      }
    });

    // Pass the modified request to the next handler
    return handle(clonedRequest);
  }
}
