// general-headers.interceptor.ts
import {Injectable} from '@angular/core';
import {HttpEvent, HttpHandler, HttpInterceptor, HttpRequest} from '@angular/common/http';
import {Observable} from 'rxjs';

@Injectable()
export class GeneralHeadersInterceptor implements HttpInterceptor {
  private token = 'eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJvaWQiOiI3Njg0NDczNS00YmEwLTQ1YjYtYjI3Zi05ZDQ0YzhjODg3ZjAiLCJzdWIiOiI3Njg0NDczNS00YmEwLTQ1YjYtYjI3Zi05ZDQ0YzhjODg3ZjAiLCJuYW1lIjoiSHVzc2VpbiBIYXNzYW4iLCJnaXZlbl9uYW1lIjoiSHVzc2VpbiIsImZhbWlseV9uYW1lIjoiSGFzc2FuIiwiam9iVGl0bGUiOiJGcm9udGVuZCBUZWNoIExlYWQiLCJlbWFpbHMiOlsiaHVzc2Vpbi5oYXNzYW5AaW50ZWdyYW50LmNvbSJdLCJleHRlbnNpb25fY3BjbGFpbV9idWNrZXRfbmFtZSI6ImNwLWludGVncmFudC0yMDIzMDIwMiIsImV4dGVuc2lvbl9jcGNsYWltX3BhcnRuZXJfaWQiOiIyN2VkNzZjZS1iZGI5LTQxZjAtYWNhMi1hMTJjNTllZDJkMTciLCJleHRlbnNpb25fY3BjbGFpbV9wYXJ0bmVyX25hbWUiOiJJbnRlZ3JhbnQiLCJleHRlbnNpb25fY3BjbGFpbV9wYXJ0bmVyX3R5cGUiOiJEaXN0cmlidXRvciIsImV4dGVuc2lvbl9jcGNsYWltX3BhcnRuZXJfc2VydmljZXMiOiJbe1wiU2VydmljZUNvZGVcIjpcImNvbXBhdGliaWxpdHlfY2hlY2tcIixcIkFsbFByb2R1Y3RzXCI6ZmFsc2V9LHtcIlNlcnZpY2VDb2RlXCI6XCJnZW5lcmFsX2Fzc2V0c1wiLFwiQWxsUHJvZHVjdHNcIjpmYWxzZX0se1wiU2VydmljZUNvZGVcIjpcInByb2R1Y3RfYXNzZXRzXCIsXCJBbGxQcm9kdWN0c1wiOmZhbHNlfSx7XCJTZXJ2aWNlQ29kZVwiOlwicHJvamVjdFwiLFwiQWxsUHJvZHVjdHNcIjpmYWxzZX0se1wiU2VydmljZUNvZGVcIjpcInJlcXVlc3RzXCIsXCJBbGxQcm9kdWN0c1wiOmZhbHNlfSx7XCJTZXJ2aWNlQ29kZVwiOlwicHJvamVjdF9hc3NldHNcIixcIkFsbFByb2R1Y3RzXCI6ZmFsc2V9LHtcIlNlcnZpY2VDb2RlXCI6XCJyZWN5Y2xhYmlsaXR5X2NoZWNrXCIsXCJBbGxQcm9kdWN0c1wiOmZhbHNlfV0iLCJ0ZnAiOiJCMkNfMV9Tb2Z0d2FyZUVuZ2luZWVyaW5nQ3VzdG9tZXJQb3J0YWxfVEVTVCIsIm5vbmNlIjoiY2RmZjdlMTAtOTJjZi00MzdhLTk1OGMtYTY5OGY0YTMyYTJkIiwic2NwIjoiYXBpLWFjY2VzcyIsImF6cCI6Ijc0MmQ3MTIyLTZlY2YtNGY5MC05ZTAxLWRlZjQwYmUxYWUxOSIsInZlciI6IjEuMCIsImlhdCI6MTcxNTQ1NTEwNiwiYXVkIjoiNTMwMDI4MjUtZjM2My00MjhiLWJhMjMtNjE1NGNlMDZiYTc5IiwiZXhwIjoxNzE1NDU4NzA2LCJpc3MiOiJodHRwczovL2FwdGFyYjJjZGV2LmIyY2xvZ2luLmNvbS9lNDI0Yjg5My1jYTU1LTQ5ZWQtYWY4Zi1kOTY4ZGE1MTgwZTIvdjIuMC8iLCJuYmYiOjE3MTU0NTUxMDZ9.nle9zVcmRkMz9RBDCNJF8_Kf4-Slt5IwLldss_OOz5arPrF9qHwKQwG2WUS1A3YC3LVrr12AvWfGPLRA1VjRDQDOjmp8eRLChXyqsC8oJKTqXTV56oRrIO2K_1dwdSEpgHKOmbjqhp7HNW0wcGlJst-2TOckN09yWxB6TwL6hs-6O7FofaTP8b6vPqGgveeHruolkDPlz_JVkurp2fjT9ti8Hwt0LuRhOKy0GajeJvu9Nsw6_DlP6zcDlbjFvoJofyg3OkQTeTd6UMQcbuE7xll34HEWko-QmotWsSKHfpGB6KJFvSrY2Tw9xeCRkV0v68brN9du7iMyAFsE2q_sqg'

  intercept(req : HttpRequest<any>, {handle} : HttpHandler) : Observable<HttpEvent<any>> {
    // Clone the request to add new headers
    const clonedRequest = req.clone({
      setHeaders: {
        'Authorization': `Bearer ${this.token}`, // Replace with actual header
        // Add more headers as needed
      }
    });

    // Pass the modified request to the next handler
    return handle(clonedRequest);
  }
}
